name: Build Index on Main

on:
  push:
    branches: [main]
    paths: "schemes/**"

  workflow_dispatch:

jobs:
  build-index:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Cache uv
        uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: uv-${{ runner.os }}-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            uv-${{ runner.os }}-

      - name: Install primaschema (pinned)
        run: |
          uv pip install "primaschema @ git+https://github.com/ChrisgKent/pha4ge-primaschema@f9e32b8" --system

      - name: Build index
        run: |
          uv run primaschema index --primer-schemes-path ./schemes  --base-url https://raw.githubusercontent.com/${{github.repository}}/main/schemes > index.json

      - name: Commit index.json if changed
        run: |
          if git diff --quiet -- index.json; then
            echo "index.json unchanged"
            exit 0
          fi
          git config user.name "primer-bot"
          git config user.email "primer-bot@users.noreply.github.com"
          git add index.json
          git commit -m "auto update index.json"
          git push
